name       : libmpack
version    : 1.0.2
release    : 3
source     :
    - https://github.com/tarruda/libmpack/archive/1.0.2.tar.gz : 9c570b2aab81b0c56d97cbd8fc483dc431b69510fd9becb4a1845291563e8bc9
license    : MIT
component  : programming
summary    : libmpack is a small binary serialization/RPC library that implements
    both the msgpack and msgpack-rpc specifications.
description: |
    libmpack is a small binary serialization/RPC library that implements both the msgpack and msgpack-rpc specifications.
builddeps  :
    - pkgconfig(lua-5.1)
build      : |
    gcc -O2 -fPIC -I/usr/include/lua5.1 -c binding/lua/lmpack.c -o lmpack.o
    gcc -shared -o mpack.so.5.1 lmpack.o
install    : |
    install -Dm755 mpack.so.5.1 $installdir/%libdir%/lua/5.1/mpack.so
