name       : libmpack
version    : 1.0.7
release    : 4
source     :
    - https://github.com/libmpack/libmpack-lua/releases/download/1.0.7/libmpack-lua-1.0.7.tar.gz : 68565484a3441d316bd51bed1cacd542b7f84b1ecfd37a8bd18dd0f1a20887e8
license    : MIT
component  : programming
summary    : Implementation of MessagePack for Lua 5.1 and Lua 5.3
description: |
    libmpack is a small binary serialization/RPC library that implements both the msgpack and msgpack-rpc specifications.
builddeps  :
    - pkgconfig(lua-5.1)
    - pkgconfig(lua-5.3)
build      : |
    gcc -O2 -fPIC -I/usr/include/lua5.1 -c lmpack.c -o lmpack-5.1.o
    gcc -shared -o mpack.so.5.1 lmpack-5.1.o

    gcc -O2 -fPIC -I/usr/include/lua5.3 -c lmpack.c -o lmpack-5.3.o
    gcc -shared -o mpack.so.5.3 lmpack-5.3.o
install    : |
    install -Dm00755 mpack.so.5.1 $installdir/%libdir%/lua/5.1/mpack.so
    install -Dm00755 mpack.so.5.3 $installdir/%libdir%/lua/5.3/mpack.so
