name       : libmpack
version    : 1.0.2
release    : 2
source     :
    - https://github.com/tarruda/libmpack/archive/1.0.2.tar.gz : 9c570b2aab81b0c56d97cbd8fc483dc431b69510fd9becb4a1845291563e8bc9
license    : MIT
component  : programming
summary    : libmpack is a small binary serialization/RPC library that implements
    both the msgpack and msgpack-rpc specifications.
description: |
    libmpack is a small binary serialization/RPC library that implements both the msgpack and msgpack-rpc specifications.
builddeps  :
    - pkgconfig(lua-5.1)
setup      : |
    mv $pkgfiles/* .
build      : |
    %make
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
